In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler 
import seaborn as sns
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.linear_model import LinearRegression
import plotly.express as px

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/digipodium/Datasets/main/house_pricing.csv")
df

In [ ]:
x=df[['Beds','Baths','SquareFeet']]
y=df['Price']

In [ ]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
print("Decision Tree")
model=DecisionTreeRegressor()
model.fit(xtrain,ytrain)
print("Score:",model.score(xtest,ytest)*100)
pred=model.predict(x)
print("Mean Absolute Error:",mean_absolute_error(y,pred))
print("Mean Squared Error:",mean_squared_error(y,pred))


In [ ]:
print("Random forest")
model1=RandomForestRegressor()
model1.fit(xtrain,ytrain)
print("Score:",model1.score(xtest,ytest)*100)
pred=model1.predict(x)
print("Mean Absolute Error:",mean_absolute_error(y,pred))
print("Mean Squared Error:",mean_squared_error(y,pred))

In [ ]:
print("Linear Regression")
model2=LinearRegression()
model2.fit(xtrain,ytrain)
print("Score:",model2.score(xtest,ytest)*100)
pred=model2.predict(x)
print("Mean Absolute Error:",mean_absolute_error(y,pred))
print("Mean Squared Error:",mean_squared_error(y,pred))

cross validation

In [28]:
tree_score=cross_val_score(model,x,y)
print("Decision Tree")
print(tree_score,"Average:",tree_score.mean())

Decision Tree
[0.79192676 0.71655704 0.67892599 0.51328527 0.61119996] Average: 0.6623790040251454


In [29]:
tree_score=cross_val_score(model1,x,y)
print("Random Forest")
print(tree_score,"Average:",tree_score.mean())

Random Forest
[0.7898593  0.71515732 0.67788555 0.49681725 0.61448307] Average: 0.6588404977315981


In [30]:
tree_score=cross_val_score(model2,x,y)
print("Linaer Regression")
print(tree_score,"Average:",tree_score.mean())

Linaer Regression
[0.88023714 0.76514106 0.72429389 0.61975165 0.49650074] Average: 0.6971848962342989


In [40]:
px.scatter_3d(df,x="Beds",y="SquareFeet",z="Baths")

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'Beds=%{x}<br>SquareFeet=%{y}<br>Baths=%{z}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': '',
              'scene': 'scene',
              'showlegend': False,
              'type': 'scatter3d',
              'x': array([2, 3, 2, ..., 3, 4, 3], dtype=int64),
              'y': array([ 836, 1167,  796, ..., 1216, 1685, 1362], dtype=int64),
              'z': array([1, 1, 1, ..., 2, 2, 2], dtype=int64)}],
    'layout': {'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'scene': {'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
                         'xaxis': {'title': {'text': 'Beds'}},
                         'yaxis': {'title': {'text': 'SquareFeet'}},
                         'zaxis': {'title': {'text': 'Baths'}}},
               'template': '...'}
})