Features Selection


In [57]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report,confusion_matrix
import seaborn as sns
import numpy as np
from matplotlib.colors import ListedColormap
from sklearn.preprocessing import StandardScaler
import plotly.express as px
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/digipodium/Datasets/main/diabetes.csv")

In [ ]:
df

In [ ]:
df.rename({'DiabetesPedigreeFunction':'pedigree'},axis=1,inplace=True)
df.head()

In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [41]:
featSelector=SelectKBest(chi2,k=7)

In [42]:
x=df.iloc[:,:-1]
x.shape
y=df['Outcome']
print(x.shape,y.shape)

(768, 8) (768,)


In [43]:
featSelector.fit(x,y)

SelectKBest(k=7, score_func=<function chi2 at 0x0000018FFAEAEDD0>)

In [44]:
featSelector.scores_

array([ 111.51969064, 1411.88704064,   17.60537322,   53.10803984,
       2175.56527292,  127.66934333,    5.39268155,  181.30368904])

In [51]:
print('columns:',featSelector.get_feature_names_out())
print('columns1:',featSelector.feature_names_in_())

columns: ['Pregnancies' 'Glucose' 'BloodPressure' 'SkinThickness' 'Insulin' 'BMI'
 'Age']


TypeError: 'numpy.ndarray' object is not callable

In [45]:
features=featSelector.transform(x)
print(features.shape)

(768, 7)


In [46]:
features

array([[  6. , 148. ,  72. , ...,   0. ,  33.6,  50. ],
       [  1. ,  85. ,  66. , ...,   0. ,  26.6,  31. ],
       [  8. , 183. ,  64. , ...,   0. ,  23.3,  32. ],
       ...,
       [  5. , 121. ,  72. , ..., 112. ,  26.2,  30. ],
       [  1. , 126. ,  60. , ...,   0. ,  30.1,  47. ],
       [  1. ,  93. ,  70. , ...,   0. ,  30.4,  23. ]])

In [47]:
scaler=StandardScaler()
scaledx =scaler.fit_transform(x)
xtrain,xtest,ytrain,ytest= train_test_split(scaledx,y,test_size=0.2)

In [48]:
model=KNeighborsClassifier()
model.fit(xtrain,ytrain)
ypred=model.predict(xtest)
cm=confusion_matrix(ytest,ypred)
print(cm)
print(classification_report(ytest,ypred))

[[80 22]
 [19 33]]
              precision    recall  f1-score   support

           0       0.81      0.78      0.80       102
           1       0.60      0.63      0.62        52

    accuracy                           0.73       154
   macro avg       0.70      0.71      0.71       154
weighted avg       0.74      0.73      0.74       154



Wrapper Method

In [53]:
from sklearn.feature_selection import RFE

In [58]:
model1=LogisticRegression()
rfe = RFE(model1)
rfe.fit(x,y)

C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


RFE(estimator=LogisticRegression())

In [59]:
rfe.get_feature_names_out()

array(['Pregnancies', 'Glucose', 'BMI', 'pedigree'], dtype=object)

In [60]:
features=x[rfe.get_feature_names_out()]
scaler=StandardScaler()
scaledx =scaler.fit_transform(x)
xtrain,xtest,ytrain,ytest= train_test_split(scaledx,y,test_size=0.2)
model=KNeighborsClassifier()
model.fit(xtrain,ytrain)
ypred=model.predict(xtest)
cm=confusion_matrix(ytest,ypred)
print(cm)
print(classification_report(ytest,ypred))

[[78 20]
 [24 32]]
              precision    recall  f1-score   support

           0       0.76      0.80      0.78        98
           1       0.62      0.57      0.59        56

    accuracy                           0.71       154
   macro avg       0.69      0.68      0.69       154
weighted avg       0.71      0.71      0.71       154

